### ISSUE TITLE
Gravestone seems to have some bugs with cultivations

### ISSUE THREAD

**Issue by lightning02** [OpenMods/OpenBlocks#787] opened 2016-07-16 18:09 UTC
I noticed that every time people die on a farmland with something planted on it, the grave appear just above but when you try to break that it drops the gravestone and not the inventory inside, also when you put down the grave on the ground and break it the grave has no items inside.
http://i.imgur.com/2T5IKZz.jpg?1
http://i.imgur.com/txRK48f.jpg?1
I'm using latest version of openblocks 1.5.1

**Comment by boq** [comment] 2016-07-16 18:29
I'm unable to reproduce it, neither by using vanilla crops nor HarvestCraft's blueberries (checked with `Pam's HarvestCraft 1.7.10Lb.jar`), so I'm guessing it's either interaction with other mod or some weird tool (since graves cannot drop as item). Is this publicly available modpack?

Second part is expected - grave does not store contents in item form.

**Comment by lightning02** [comment] 2016-07-16 18:44
Here it is http://www.technicpack.net/modpack/rise-of-humanity-ultra-lite.872978 
it's a modpack that I play with my bf and a couple of friends occasionally, btw if I can do something more for you just tell me :o

**Comment by boq** [comment] 2016-07-16 20:48
It took me ridiculous amount of time to load Minecraft, then world (really, how beefy computer one needs to play it?), place all blocks, die and... all items drops. So still cannot reproduce...

**Comment by lightning02** [comment] 2016-07-16 21:00
uhm, I run that with a gtx 960 :o the only annoyng thing is the loading time, btw, did you died on a farmland with something planted on it?

**Comment by boq** [comment] 2016-07-16 21:03
Yes, I more or less recreated your screenshot.

I have no idea what can cause such drops, Only thing I can think of is of somehow one of the mods replaces normal drops with creative "pick up" (middle click) ones. But that makes no sense...

**Comment by lightning02** [comment] 2016-07-16 21:15
we usually run the modpack using thermos, could this interfere in some way?

**Comment by boq** [comment] 2016-07-16 21:16
Very likely.

**Comment by lightning02** [comment] 2016-07-16 21:25
I'v just now tryed on single-player, I guess thermos has nothing to do with it, idk why I can still reproduce it :/
http://i.imgur.com/r87fJWg.jpg
http://i.imgur.com/hEUXyeZ.jpg

**Comment by lightning02** [comment] 2016-07-16 21:36
http://i.imgur.com/BeYyELQ.jpg
If I break the crops underneath the gravestone fall dawn (because of gravity from enviromine) then it has no name on it and no item stored

**Comment by boq** [comment] 2016-07-16 21:38
Wait, what, "falls down"? This is absolutely not supported and I refuse to debug such stupidity.

**Comment by lightning02** [comment] 2016-07-16 21:46
I'm not 100% sure that the other problem is from evnriomine too, (the fact that the grave on crops drops on hand instead of breaks), should I report it to them? By the way, why the gravestone override-block function doesn't work at all? :C

**Comment by boq** [comment] 2016-07-16 21:49
Not sure if enviromine is responsible for "falling sand" effect, doesn't seem to be on their feature list.

Also, do you mean "destructiveGraves" option? This is second chance strategy, i.e. will only work if it's impossible to place without replacing block (i.e. suffocating in giant cube of solid blocks).

**Comment by lightning02** [comment] 2016-07-16 22:05
for the "falling sand effect" could perfectly be, enviromine has a function that allow basic physic to the game and every block is affected, so this is almost sure it would be enviromine, but about the fact that the tomb generate up to the crops and then doesn't break but drops on hand.. i don't know what could it be '-'

**Comment by boq** [comment] 2016-07-16 22:54
Ok, I see it, it's definitely all enviromine fault. And now I'm pissed off for how much time I wasted debugging problems caused by that idiotic code.

Notice that normally it takes couple seconds to break block, but here it breaks after first click - it's because it's not broken, only updated and converted into "falling sand" container block, which in turn is broken by crops (same code as vanilla sand). Can be also triggered by placing block next to grave.

I had problems with reproduction, since I places my crops near wall - so all blocks were supported.

Here are problems with EntityPhysicsBlock that cause faulty behaviour:
- `this.entityDropItem(new ItemStack(this.block, 1, this.block.damageDropped(this.meta)), 0.0F);` on drop - it's **completely wrong** - this ignores almost all customizations block can have, including custom tile entity drops (or actually any custom drop - line ones added in `Block.getDrops`).
- restoring TE data only when block implements `ITileEntityProvider`. Really!?, `Block.hasTileEntity` has existed for couple of years.

So, I'm closing this issue. Tell enviromine authors, that before they want to move anything else than dirt, they have to learn how this game works.

**Closed by boq** 2016-07-16 22:54 UTC

**Comment by lightning02** [comment] 2016-07-16 23:30
Man, let me say a thing, you are one of the most kind and patient person around modding comunity, there are few like you...
Thanks alot for your effort, it's really really appriciated.
Your information will be precious and I will notify to the enviromine author.
I believe that resolving mods incompatibilities make minecraft a better place and can offer a very interesting an plenty experience.
Thansk alot for helping and for all your hard work ! :)

**Comment by PitchBright** [comment] 2016-07-17 13:08
@lightning02 Why didn't you just set the gravestone block to not drop, in the Enviromine configs?

**Comment by boq** [comment] 2016-07-17 13:13
From my point of view, it should be opt-in and default configs should contain only blocks that are confirmed to be compatible. Custom drops and moving TEs are way too complicated to just assume it will work with any block.

**Comment by PitchBright** [comment] 2016-07-17 13:17
When you say "opt-in"... what do you mean?

**Comment by boq** [comment] 2016-07-17 13:19
Whitelist of blocks that can be dropped. I'm not sure how it works right now, but enviromine by default drops graves, so there is probably some "default" setting.

**Comment by PitchBright** [comment] 2016-07-17 13:29
Oh. Well what happens is, the user surely knows it's a physics mod, before adding it... and then turns physics "on" in the configs... and then sets the mod to auto-generate base settings for each block (and a variety of other things). That gives the user a template to work from so they can customize all their stuff (blocks, etc), and then fine-tune their experience.

Conversely, the user would enable physics, not generate templates, and then manually add blocks they want to have physics for... not that I can imagine anybody going that route, because it would be a terribly arduous task to config it from scratch, even if no other mods were present. So with that said, I think anybody who just turns physics on, let's EM generate settings for every single block in every single mod, without testing anything, and assumes that every-single-block is gonna behave itself... is pipe-dreaming. Especially when considering that each block's physics can be configured in myriad ways. How could the EM authors know exactly how ABC user wants XYZ Block from LMNOP mod to behave in-game. They couldn't possibly... so they give you the foundation, and do 95% of the dirty work for ya... and then let you tweak stuff as desired.

**Comment by boq** [comment] 2016-07-17 13:37
Well, not my design decision. Anyway, it closed issue and it's up to them to fix it.

Though it's my opinion that when you do something risky and mess with other mods, either do it right and test every case you can imagine or don't bother. Because if block X does not work due to broken mechanics in Y, who will get bug report?

**Comment by PitchBright** [comment] 2016-07-17 13:41
User should have clued in right off the hop, that because physics was being applied to the block, it changed the way the block works. It should never have been brought to your attention.

I'm not sure what part of the code you're seeing as problematic, but I'll take your word for it that there's a better way to do what you're seeing. Worth considering though, it's possible that they did test every case they could imagine, but didn't imagine whatever it is that the gravestone is/does?

**Comment by boq** [comment] 2016-07-17 13:45
No. The only thing they tested are probably vanilla blocks. Though even some of those are broken (like double slabs drops).

Anyway, no point in continuing this discussion.

**Comment by lightning02** [comment] 2016-07-17 13:53
The first thing I've done when I noticed this problem was updating openblocks... I knew about enviromine physics but I had no clue it could be that mod involved until I broke the crop underneath and discovered the "falling behavior".. I wouldn't have bothered if that was clear from beginning...
By the way, now seems there is a config way to fix it, that's the matter :c
PitchBright, how exactly should people operate to blacklist gravestone in the config making them don't being affected by enviromine physics?
