### ISSUE TITLE
[Feature Request]IGW (In-Game Wiki) support

### ISSUE THREAD

**Issue by soulgriever** [OpenMods/OpenBlocks#697] opened 2015-08-29 01:51 UTC
![2015-08-28_21 23 41](https://cloud.githubusercontent.com/assets/2360198/9559882/2321693e-4dcb-11e5-8a45-0422c23e0dea.png)
![2015-08-28_21 23 58](https://cloud.githubusercontent.com/assets/2360198/9559883/2323a6ea-4dcb-11e5-88d9-5d5948837c5d.png)
Wiki in game you can press I and view description of block you are looking at also good for explaining on how to use machines or tools such as book press
https://github.com/MineMaarten/IGW-mod

**Comment by TheSilkMiner** [comment] 2015-09-13 14:13
Since no one has answered in all this time, I thought I could give this a go.
The problem is that OpenBlocks has already an info-book, which works the same as IGW, so I don't know if this would be accepted. I reckon this would be really useful if the book isn't available or it's lost (even though it is easily recraftable).

If this **could** be accepted, I can try to find out how IGW creates its pages.

**Comment by boq** [comment] 2015-09-13 14:41
It's somewhere on my TODO list. I could probably use existing information, used for book to create IGW pages.

**Comment by TheSilkMiner** [comment] 2015-09-14 15:50
I have tried to create a page for IGW (which is simple by the way: just a `txt` file), but as soon as I tried to read it in-game, I encountered a problem.

If I shade the page file into OpenBlocks's jar file, this happens: ![Shaded assets](https://cloud.githubusercontent.com/assets/11136677/9852522/052d7c2e-5aff-11e5-827e-acf69dcc380a.png)

If I load the resource pack I used to edit the page, everything is fine instead: ![Resource pack](https://cloud.githubusercontent.com/assets/11136677/9852937/43edd5ec-5b01-11e5-8751-13bc5fcee1e5.png)

I think this could be an issue with the implementation because I don't think it is a good idea to force OpenBlocks users to also add a resource pack.

**Comment by boq** [comment] 2015-12-26 20:25
Closing; please see https://github.com/OpenMods/OpenMods-IGW

**Closed by boq** 2015-12-26 20:25 UTC
