### ISSUE TITLE
Hang Glider can't use in server

### ISSUE THREAD

**Issue by xjboss** [OpenMods/OpenBlocks#654] opened 2015-05-16 04:49 UTC
Hang Glider can't use in server .
But single player mode can use it .
I use kcauldron 1403 server .
It's happening since openblock 1.4.2 . I use openblock 1.4.3 , but this bug not be repaired.

**Comment by boq** [comment] 2015-05-16 09:07
What do you mean by "can't use"? I can't reproduce this issue, hang glider deploys normally, even on server.

**Comment by xjboss** [comment] 2015-05-19 13:36
Sorry ,it not beause of cauldron it might because of bungee . I found no bungee to link it can work , but on bungee it can't work .

**Comment by xjboss** [comment] 2015-05-19 13:42
Sorry ,it not beause of cauldron it might because of bungee . I found no bungee to link it can work , but on bungee it can't work .

**Comment by xjboss** [comment] 2015-05-19 13:43
Sorry ,it not beause of cauldron. it might because of bungee . I found no bungee to link it can work , but on bungee it can't work .

**Comment by xjboss** [comment] 2015-05-19 13:44
Sorry ,it not beause of mod version and server. it might because of bungee . I found no bungee to link it can work , but on bungee it can't work .

**Comment by xjboss** [comment] 2015-05-19 13:44
Sorry , I found it not beause of mod version and server. it might because of bungee . I found no bungee to link it can work , but on bungee it can't work .

**Comment by boq** [comment] 2015-11-09 20:58
Closing, since it looks like bungee problem.

**Closed by boq** 2015-11-09 20:58 UTC
