### ISSUE TITLE
Drawing Table UI Bug

### ISSUE THREAD

**Issue by zakdwyer** [OpenMods/OpenBlocks#656] opened 2015-05-20 02:24 UTC
It appears that with the majority of the available stencils in the Drawing Table, many of the selections' images are scaled incorrectly. A few of them are fine.

![regular drawing table](https://cloud.githubusercontent.com/assets/5987504/7717790/2bc9180c-fe75-11e4-918f-13e2c978e317.png)
![buggy drawing table](https://cloud.githubusercontent.com/assets/5987504/7717792/2f126f36-fe75-11e4-9e28-c87df4cbf5ad.png)
![buggy drawing table 2](https://cloud.githubusercontent.com/assets/5987504/7717794/30d5f716-fe75-11e4-94e1-88159fb257a3.png)

**Minecraft version:** 1.7.10
**Forge version:** 10.13.3.1407-1.7.10
**Mods being used:**
![mod list](https://cloud.githubusercontent.com/assets/5987504/7717820/cb85e9b0-fe75-11e4-9bb5-cf75ff0fc005.png)

**Comment by boq** [comment] 2015-05-20 16:57
They are all oversized. Some of them look correct even when doubled, but they still have wrong size. Here how first one should look like:
![normal](https://cloud.githubusercontent.com/assets/754542/7731469/fbf3003c-ff20-11e4-8e03-39d6a7aa6c83.png)

I can't reproduce that one, so I guess it's interaction with one of items in inventory or other mods. Try with empty inventory and then with disabled NEI.

**Comment by zakdwyer** [comment] 2015-05-21 07:04
I have removed all of the mods except for OpenModsLib and OpenBlocks itself. I'm still getting the same issue:
![image](https://cloud.githubusercontent.com/assets/5987504/7743167/129a2ef6-ff66-11e4-80f7-8623b909047d.png)

**Comment by boq** [comment] 2015-05-21 15:13
Sorry, I still can't reproduce (even after adding NEI). Though I haven't tried optifine, but that's generally unsupported. Please make sure you have most recent version of all mods, directly from openmods.info (OB is at 1.4.3, OM 0.7.3)

**Comment by boq** [comment] 2015-12-26 20:34
No extra information, no reproducible. Closing.

**Closed by boq** 2015-12-26 20:34 UTC
