### ISSUE TITLE
[Bug] Opening the "World dominations with OpenBlocks" book crashes the game back to the menu

### ISSUE THREAD

**Issue by SnowShock35** [OpenMods/OpenBlocks#576] opened 2015-01-09 22:35 UTC
Hi,

I believe I found a bug with OpenBlocks, here are the details...

Minecraft Version: 1.7.10
Forge Version: 10.13.2.1277
OpenBlocks: 1.7.10-1.3
OpenModsLib: 1.7.10-0.6

Description: When in the game and holding the World Domination with OpenBlocks book, Right clicking the book causes the game to crash and bring you to a dirt screen that says "Connection Lost A fatal error has occured, this connection is terminated" (Screenshot bellow).

![](https://i.imgur.com/Icbmugr.png)

Log: (From when I right clicked the book) https://paste.ee/p/GDBxz

**Comment by boq** [comment] 2015-01-10 10:48
Duplicate of #568 - bug in other mod. Either wait for MachineMuse/MachineMusePowersuits#561 to be resolved or update to [this](http://www.openmods.info:8080/job/OpenModsLib/283/).

**Closed by boq** 2015-01-10 10:48 UTC
